language: cpp
os:
  - linux
compiler:
  - g++
install:
  - sudo pip install codecov
script:
  - make -C homework/HW1/triangle_problem_test
  - make -C homework/HW1/NextDate_problem_test
  - make -C homework/HW1/Commission_problem_test
  - ./homework/HW1/triangle_problem_test/triangle_verifier_unittest
  - ./homework/HW1/NextDate_problem_test/NextDate_verifier_unittest
  - ./homework/HW1/Commission_problem_test/Commission_verifier_unittest
  - cd homework/HW1/triangle_problem_test/
  - gcov triangle_verifier.cpp
  - cd -
  - cd homework/HW1/NextDate_problem_test/
  - gcov NextDate_verifier.cpp
  - cd -
  - cd homework/HW1/Commission_problem_test/
  - gcov Commission_verifier.cpp
  - cd -
branches:
  only:
    - master

after_success:
  - codecov -t 52e56ebb-ca11-48c8-bc59-ef634d951d12 -X gcov
